name: ledatelescope_bifrost_doc_env

channels:
  - conda-forge

dependencies:
  - numpy
  - python
  - scipy
  - sphinx
  - pip
  - simplejson
  - ctypesgen
  - setuptools
  - breathe
  - pip:
    - pint
